### ISSUE TITLE
openNextAttachmentInOpenedEmail missing?

### ISSUE THREAD

**Issue by ervaude** [koehnlein/codeception-email-mailpit#6]
Hi Albrecht,

about `openNextAttachmentInOpenedEmail()`:

The Readme mentions this method couple of times and I really wish it would exist, but it does not.

Or am I missing something?

**Comment by koehnlein** [comment]
The [method exists here](https://github.com/koehnlein/codeception-email-mailpit/blob/923bf6b54b01ee9b6f350ae0498abbd0cf2ae1ef/src/Mailpit.php#L214) and was introduced with #3 from @eliashaeussler - Maybe he can give better support in this case?

**Comment by eliashaeussler** [comment]
@ervaude As @koehnlein already wrote, this method indeed exists as you can also see here: https://github.com/eliashaeussler/typo3-form-consent/blob/2.1.0/Tests/Acceptance/Frontend/Domain/Finishers/ConsentFinisherCest.php#L156

**Comment by ervaude** [comment]
Yes, you are both right.

I was blind, but now I see.

I failed to properly update my composer package ...

Thanks for the hints!
